import 'wish_module.dart';

/// File templates for AppLoop-generated apps. [renderAppFiles] fills the
/// `__PLACEHOLDERS__` and returns the full `lib/` file set for one module.
/// Every template is a complete, analyzer-clean Flutter file.
class AppTemplate {
  /// Escapes arbitrary text for a single-quoted Dart string literal.
  static String escapeDartString(String text) {
    return text
        .replaceAll('\\', '\\\\')
        .replaceAll("'", "\\'")
        .replaceAll('\$', '\\\$')
        .replaceAll('\n', '\\n');
  }

  /// Renders all `lib/` files for [module]. Values must already be escaped.
  static Map<String, String> renderAppFiles({
    required WishModule module,
    required String wishTitle,
    required String wishDescription,
    required String seedColor,
  }) {
    final main = _mainTemplate
        .replaceAll('__MODULE_FILE__', module.fileName)
        .replaceAll('__MODULE_WIDGET__', module.widgetName);
    final wish = _wishTemplate
        .replaceAll('__WISH_TITLE__', wishTitle)
        .replaceAll('__WISH_DESCRIPTION__', wishDescription)
        .replaceAll('__SEED_COLOR__', seedColor);
    return {
      'lib/main.dart': main,
      'lib/wish.dart': wish,
      'lib/modules/${module.fileName}': _moduleTemplates[module]!,
    };
  }

  /// Renders the widget test for a generated app. [packageName] is the
  /// snake_case project name.
  static String renderWidgetTest(String packageName) {
    return _widgetTestTemplate.replaceAll('__PACKAGE__', packageName);
  }

  static const _widgetTestTemplate = '''
import 'package:flutter_test/flutter_test.dart';

import 'package:__PACKAGE__/main.dart';
import 'package:__PACKAGE__/wish.dart';

void main() {
  testWidgets('shows the wish title', (tester) async {
    await tester.pumpWidget(const GeneratedApp());
    expect(find.text(WishInfo.title), findsWidgets);
  });
}
''';

  static const _mainTemplate = '''
// Generated by AppLoop. Do not edit by hand — it is rewritten on every
// iteration from the wish. Hand-written code belongs elsewhere.
import 'package:flutter/material.dart';

import 'modules/__MODULE_FILE__';
import 'wish.dart';

void main() {
  runApp(const GeneratedApp());
}

class GeneratedApp extends StatelessWidget {
  const GeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: WishInfo.title,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: WishInfo.seedColor),
        useMaterial3: true,
      ),
      home: const __MODULE_WIDGET__(),
    );
  }
}
''';

  static const _wishTemplate = '''
import 'package:flutter/material.dart';

/// The wish this build was generated from.
abstract final class WishInfo {
  static const title = '__WISH_TITLE__';
  static const description = '__WISH_DESCRIPTION__';
  static const seedColor = Color(__SEED_COLOR__);
}
''';

  static const _moduleTemplates = {
    WishModule.counter: _counterTemplate,
    WishModule.notes: _notesTemplate,
    WishModule.checklist: _checklistTemplate,
    WishModule.quiz: _quizTemplate,
  };

  /// Header shared by the generated screens, defined once per module file.
  static const _headerDef = '''
/// Wish header shared by the generated screens.
Widget _wishHeader(BuildContext context) {
  final theme = Theme.of(context);
  return Padding(
    padding: const EdgeInsets.all(16),
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(WishInfo.title, style: theme.textTheme.headlineSmall),
        if (WishInfo.description.isNotEmpty) ...[
          const SizedBox(height: 4),
          Text(WishInfo.description, style: theme.textTheme.bodyMedium),
        ],
      ],
    ),
  );
}
''';

  static const _counterTemplate =
      '''
import 'package:flutter/material.dart';

import '../wish.dart';
$_headerDef

/// Tap counter with a wish header.
class CounterScreen extends StatefulWidget {
  const CounterScreen({super.key});

  @override
  State<CounterScreen> createState() => _CounterScreenState();
}

class _CounterScreenState extends State<CounterScreen> {
  int _count = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(WishInfo.title)),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
_wishHeader(context),
          Expanded(
            child: Center(
              child: Text(
                '\$_count',
                style: Theme.of(context).textTheme.displayLarge,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                FilledButton.tonal(
                  onPressed: () => setState(() => _count--),
                  child: const Icon(Icons.remove),
                ),
                FilledButton.tonal(
                  onPressed: () => setState(() => _count = 0),
                  child: const Text('Reset'),
                ),
                FilledButton(
                  onPressed: () => setState(() => _count++),
                  child: const Icon(Icons.add),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
''';

  static const _notesTemplate =
      '''
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../wish.dart';
$_headerDef

/// Notes with on-device persistence.
class NotesScreen extends StatefulWidget {
  const NotesScreen({super.key});

  @override
  State<NotesScreen> createState() => _NotesScreenState();
}

class _NotesScreenState extends State<NotesScreen> {
  static const _prefsKey = 'apploop_notes';
  final _controller = TextEditingController();
  List<String> _notes = [];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final prefs = await SharedPreferences.getInstance();
    if (!mounted) return;
    setState(() {
      _notes = prefs.getStringList(_prefsKey) ?? [];
      _loading = false;
    });
  }

  Future<void> _save() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setStringList(_prefsKey, _notes);
  }

  void _add() {
    final text = _controller.text.trim();
    if (text.isEmpty) return;
    setState(() {
      _notes = [..._notes, text];
      _controller.clear();
    });
    _save();
  }

  void _removeAt(int index) {
    setState(() {
      _notes = [..._notes]..removeAt(index);
    });
    _save();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text(WishInfo.title)),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
_wishHeader(context),
          if (_loading)
            const Expanded(child: Center(child: CircularProgressIndicator()))
          else if (_notes.isEmpty)
            const Expanded(child: Center(child: Text('No notes yet.')))
          else
            Expanded(
              child: ListView.builder(
                itemCount: _notes.length,
                itemBuilder: (context, index) {
                  return Dismissible(
                    key: ValueKey('\${index}_\${_notes[index]}'),
                    direction: DismissDirection.endToStart,
                    background: Container(
                      color: Theme.of(context).colorScheme.errorContainer,
                      alignment: Alignment.centerRight,
                      padding: const EdgeInsets.only(right: 16),
                      child: const Icon(Icons.delete),
                    ),
                    onDismissed: (_) => _removeAt(index),
                    child: ListTile(title: Text(_notes[index])),
                  );
                },
              ),
            ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: const InputDecoration(
                      labelText: 'New note',
                      border: OutlineInputBorder(),
                    ),
                    onSubmitted: (_) => _add(),
                  ),
                ),
                const SizedBox(width: 8),
                FilledButton(
                  onPressed: _add,
                  child: const Icon(Icons.add),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
''';

  static const _checklistTemplate =
      '''
import 'package:flutter/material.dart';

import '../wish.dart';
$_headerDef

/// Checklist with add-your-own items.
class ChecklistScreen extends StatefulWidget {
  const ChecklistScreen({super.key});

  @override
  State<ChecklistScreen> createState() => _ChecklistScreenState();
}

class _ChecklistScreenState extends State<ChecklistScreen> {
  final _controller = TextEditingController();
  final List<({String label, bool done})> _items = [
    (label: 'Try the main flow', done: false),
    (label: 'Rotate the phone', done: false),
    (label: 'Check dark mode', done: false),
  ];

  void _add() {
    final text = _controller.text.trim();
    if (text.isEmpty) return;
    setState(() {
      _items.add((label: text, done: false));
      _controller.clear();
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final done = _items.where((item) => item.done).length;
    return Scaffold(
      appBar: AppBar(title: const Text(WishInfo.title)),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
_wishHeader(context),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text('\$done of \${_items.length} done'),
          ),
          Expanded(
            child: ListView.builder(
              itemCount: _items.length,
              itemBuilder: (context, index) {
                final item = _items[index];
                return CheckboxListTile(
                  title: Text(item.label),
                  value: item.done,
                  onChanged: (value) {
                    setState(() {
                      _items[index] = (label: item.label, done: value ?? false);
                    });
                  },
                );
              },
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(16),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: const InputDecoration(
                      labelText: 'New item',
                      border: OutlineInputBorder(),
                    ),
                    onSubmitted: (_) => _add(),
                  ),
                ),
                const SizedBox(width: 8),
                FilledButton(
                  onPressed: _add,
                  child: const Icon(Icons.add),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
''';

  static const _quizTemplate =
      '''
import 'package:flutter/material.dart';

import '../wish.dart';
$_headerDef

/// Short quiz about the wish itself, with a score.
class QuizScreen extends StatefulWidget {
  const QuizScreen({super.key});

  @override
  State<QuizScreen> createState() => _QuizScreenState();
}

class _QuizScreenState extends State<QuizScreen> {
  int _index = 0;
  int _score = 0;
  bool _answered = false;
  int? _picked;

  List<({String question, List<String> options, int answer})> get _questions {
    return [
      (
        question: 'What is this app called?',
        options: [WishInfo.title, 'Something else', 'Not sure yet'],
        answer: 0,
      ),
      (
        question: 'What is it for?',
        options: [
          WishInfo.description.isEmpty
              ? 'Whatever you wish'
              : WishInfo.description,
          'Nothing in particular',
          'Everything at once',
        ],
        answer: 0,
      ),
      (
        question: 'How was this build made?',
        options: ['By AppLoop', 'By hand', 'By magic'],
        answer: 0,
      ),
    ];
  }

  void _answer(int picked) {
    if (_answered) return;
    setState(() {
      _answered = true;
      _picked = picked;
      if (picked == _questions[_index].answer) _score++;
    });
  }

  void _next() {
    setState(() {
      _index++;
      _answered = false;
      _picked = null;
    });
  }

  void _restart() {
    setState(() {
      _index = 0;
      _score = 0;
      _answered = false;
      _picked = null;
    });
  }

  @override
  Widget build(BuildContext context) {
    final questions = _questions;
    return Scaffold(
      appBar: AppBar(title: const Text(WishInfo.title)),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
_wishHeader(context),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: _index >= questions.length
                  ? Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Text(
                          'Score: \$_score / \${questions.length}',
                          style: Theme.of(context).textTheme.headlineMedium,
                        ),
                        const SizedBox(height: 16),
                        FilledButton(
                          onPressed: _restart,
                          child: const Text('Play again'),
                        ),
                      ],
                    )
                  : Column(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
                        Text(
                          'Question \${_index + 1} of \${questions.length}',
                          style: Theme.of(context).textTheme.titleMedium,
                        ),
                        const SizedBox(height: 8),
                        Text(questions[_index].question),
                        const SizedBox(height: 16),
                        for (var i = 0;
                            i < questions[_index].options.length;
                            i++)
                          Padding(
                            padding: const EdgeInsets.only(bottom: 8),
                            child: FilledButton.tonal(
                              style: FilledButton.styleFrom(
                                backgroundColor: !_answered
                                    ? null
                                    : i == questions[_index].answer
                                        ? Colors.green.withValues(alpha: 0.3)
                                        : i == _picked
                                            ? Colors.red
                                                .withValues(alpha: 0.3)
                                            : null,
                              ),
                              onPressed: () => _answer(i),
                              child: Text(questions[_index].options[i]),
                            ),
                          ),
                        if (_answered) ...[
                          const SizedBox(height: 8),
                          FilledButton(
                            onPressed: _next,
                            child: Text(
                              _index + 1 >= questions.length
                                  ? 'See score'
                                  : 'Next',
                            ),
                          ),
                        ],
                      ],
                    ),
            ),
          ),
        ],
      ),
    );
  }
}
''';
}
